spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seekers?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: HBC13579
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false



server:
  port: 8080

logging:
  level:
    com.hbc: debug
    org.springframework: info

mybatis:
  type-aliases-package: com.hbc.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



